export const dummyProducts = [
  {
    name: "Fancy chair",
    image: "./images/img.1",
    brand: "Fako",
    category: "Accessoires",
    description: "This is a very fancy product from Fako brand",
    price: 20.99,
    countInStock: 21,
  },
  {
    name: "BackPack",
    image: "./images/img.2",
    brand: "Fako",
    category: "Accessoires",
    description: "This is a very fancy product from Fako brand",
    price: 18.99,
    countInStock: 15,
  },
  {
    name: "shawl",
    image: "./images/img.3",
    brand: "Fako",
    category: "Accessoires",
    description: "This is a very fancy product from Fako brand",
    price: 5.99,
    countInStock: 4,
  },
  {
    name: "clock",
    image: "./images/img.4",
    brand: "Fako",
    category: "Accessoires",
    description: "This is a very fancy product from Fako brand",
    price: 10.99,
    countInStock: 10,
  },
];
